name: BetterNetheriteUpgrading
version: 1.0
main: link.star_dust.BetterNetheriteUpgrading.Main
api-version: 1.20
description: A plugin to adjust Netherite upgrading cost based on item type.
commands: {}
permissions: {}
